// Type-only import: erased at runtime, so importing this module never binds
// rm3-shared's copy of oxlint into a consumer's process. `defineConfig` is
// deliberately never CALLED here — the consumer calls it on its own oxlint.
import type { OxlintConfig } from 'oxlint';

import { antiSlopRules, antiSlopRulesOff, complexityRules } from '@rm3/lint';

export { antiSlopRules, antiSlopRulesOff, complexityRules };

/**
 * Plugins a React consumer adds in an override over its React source tree.
 * They are not in `rm3Config.plugins`: an explicit plugin list REPLACES
 * oxlint's defaults, so a non-React repo must not pay for them.
 */
export const reactPlugins = ['react', 'react-perf', 'jsx-a11y'] as const;

/**
 * The rules `reactRulesOff` turns off, named so the binding has an owner
 * contract instead of an inline object type. The annotation itself is
 * load-bearing: it keeps each value at the literal `'off'` while leaving the
 * object mutable, which is the shape oxlint's `Config['rules']` accepts.
 */
type ReactRulesOff = {
  'jsx-a11y/label-has-associated-control': 'off';
  'react-perf/jsx-no-jsx-as-prop': 'off';
  'react-perf/jsx-no-new-array-as-prop': 'off';
  'react-perf/jsx-no-new-function-as-prop': 'off';
  'react-perf/jsx-no-new-object-as-prop': 'off';
  'react/react-in-jsx-scope': 'off';
};

/** Rules to turn off in a React override, keyed the way oxlint names them. */
export const reactRulesOff: ReactRulesOff = {
  // React 17+ JSX transform doesn't require React in scope
  'react/react-in-jsx-scope': 'off',
  // Inline callbacks and literals in props are the normal React idiom;
  // memoizing every one of them costs more than it saves.
  'react-perf/jsx-no-jsx-as-prop': 'off',
  'react-perf/jsx-no-new-array-as-prop': 'off',
  'react-perf/jsx-no-new-function-as-prop': 'off',
  'react-perf/jsx-no-new-object-as-prop': 'off',
  // Generic Label component — htmlFor passed via props
  'jsx-a11y/label-has-associated-control': 'off',
};

/**
 * Rules to turn off over vendored shadcn primitives. These are generated by
 * `shadcn add` and re-generated on upgrade, so no rule here may force an edit
 * that the next regeneration deletes — every style rule upstream trips is off.
 * Correctness and type-aware rules stay on, so a real bug still reports.
 */
export const shadcnRulesOff = {
  // Regenerated by `shadcn add`; SAFETY comments would not survive.
  ...antiSlopRulesOff,
  'import/no-namespace': 'off',
  // These a11y rules are about the wrapper markup Base UI expects
  // (`role="group"` on an input group, `role="link"` on a breadcrumb),
  // which the primitives already handle correctly underneath.
  'jsx-a11y/click-events-have-key-events': 'off',
  'jsx-a11y/no-noninteractive-element-interactions': 'off',
  'jsx-a11y/prefer-tag-over-role': 'off',
  // Style rules upstream shadcn does not follow. Each one would force an
  // edit that the next `shadcn add` overwrites.
  curly: 'off',
  eqeqeq: 'off',
  'react/no-array-index-key': 'off',
  'typescript/array-type': 'off',
  // Hundreds of hits across the primitives. The prop and key order is upstream's.
  'perfectionist/sort-enums': 'off',
  'perfectionist/sort-heritage-clauses': 'off',
  'perfectionist/sort-interfaces': 'off',
  'perfectionist/sort-jsx-props': 'off',
  'perfectionist/sort-object-types': 'off',
  'perfectionist/sort-objects': 'off',
} satisfies NonNullable<OxlintConfig['rules']>;

export const rm3Config: OxlintConfig = {
  categories: {
    // Code that is outright wrong or useless
    correctness: 'error',
    // Code that is most likely wrong or useless
    suspicious: 'error',
    // Strict rules with occasional false positives
    pedantic: 'warn',
    // Rules that aim to improve runtime performance
    perf: 'warn',
    // `style` is off: oxfmt owns formatting, and the rest of the category
    // (sort-keys, no-ternary, import/no-named-export) is preference that
    // produced ~1,300 warnings in the repo this came from. `curly` was the one
    // worth having, so it is opted into individually below.
    // `restriction` is off: feature ban-lists; the few we want are opted into
    // individually below.
    // `nursery` is off: unstable by definition, so it breaks lint on upgrade.
  },
  // builtin + es2024 only; a consumer adds `node`, `browser` or `serviceworker`
  // itself, because the right answer differs per repo and per directory.
  env: {
    builtin: true,
    es2024: true,
  },
  jsPlugins: [
    // `import.meta.resolve` runs HERE, inside rm3-shared, so the specifiers
    // resolve from rm3-shared/node_modules even when a consumer reaches this
    // file through a `link:` symlink.
    {
      name: 'perfectionist',
      specifier: import.meta.resolve('eslint-plugin-perfectionist'),
    },
    // Vendored anti-slop rules. Source-only package, loaded straight from .ts.
    {
      name: 'anti-slop',
      specifier: import.meta.resolve('@rm3/lint'),
    },
  ],
  options: {
    // tsgolint type-aware rules, plus TypeScript compiler diagnostics. Both are
    // on here so a plain `pnpm lint` is the full check; CLI flags still take
    // precedence over this file.
    typeAware: true,
    typeCheck: true,
  },
  overrides: [
    {
      // Cyclomatic complexity counts every `&&` and ternary as a branch. In a
      // render body those are a display ladder, not control flow: a component
      // that shows one of four states scores the same as a four-way algorithm.
      // The rule measures the wrong thing here, so it is off for markup and
      // stays on for the `.ts` logic those components call.
      files: ['**/*.tsx'],
      rules: { complexity: 'off' },
    },
    {
      // Build tooling reads untyped JSON and third-party config types.
      files: ['*.config.ts'],
      rules: {
        'typescript/no-unsafe-assignment': 'off',
        'typescript/no-unsafe-member-access': 'off',
        // e.g. Vite's rollupOptions -> rolldownOptions
        'typescript/no-deprecated': 'off',
      },
    },
    {
      // `node:test` returns a promise from `describe` and `test` that the
      // runner itself awaits — the whole API is built on not awaiting them at
      // the call site. Tests sit next to the module they cover, so match by
      // suffix rather than by directory.
      files: ['**/*.test.ts'],
      rules: {
        'typescript/no-floating-promises': 'off',
        // Tests set and swap environment variables directly. That is exactly
        // what a lazy env reader exists to serve.
        'node/no-process-env': 'off',
      },
    },
  ],
  // Universal plugins only; React lives in a consumer-side override.
  // An explicit list REPLACES oxlint's defaults, so `typescript`, `unicorn`,
  // and `oxc` must be named here or they are silently dropped — and with
  // `typescript` gone, every type-aware rule stops running.
  plugins: ['typescript', 'unicorn', 'oxc', 'import', 'node', 'promise'],
  rules: {
    // Would require readonly-wrapping nearly every React prop and Node option
    // object. Many hits, none of them bugs.
    'typescript/prefer-readonly-parameter-types': 'off',
    // Fights idiomatic `if (str)` / `if (arr.length)`.
    'typescript/strict-boolean-expressions': 'off',
    // Fights `onClick={() => doThing()}`, the standard React handler shape.
    'typescript/no-confusing-void-expression': 'off',
    // Assertions are a deliberate escape hatch at schema boundaries.
    'typescript/no-unsafe-type-assertion': 'off',
    // Trusts the declared types over runtime reality, which is backwards for
    // this kind of code: the guards it flags sit on host APIs that are absent
    // in some environments, on JSON read back off disk, and on index lookups.
    // Deleting them is how code starts throwing in the environments the types
    // don't describe.
    'typescript/no-unnecessary-condition': 'off',
    // Fastify hooks return `reply` to signal "response already sent" and
    // nothing to continue; React effects return a cleanup or nothing. Both
    // contracts are mixed-return by design.
    'typescript/consistent-return': 'off',

    // --- Type-aware rules worth having ---
    'typescript/consistent-type-exports': 'warn',
    'typescript/dot-notation': 'warn',
    'typescript/no-floating-promises': 'error',
    'typescript/no-misused-promises': 'error',
    'typescript/no-unnecessary-qualifier': 'warn',
    'typescript/no-unnecessary-type-conversion': 'warn',
    'typescript/no-unnecessary-type-parameters': 'warn',
    'typescript/no-useless-default-assignment': 'warn',
    'typescript/prefer-find': 'warn',
    // `||` on a string is almost always a deliberate empty-string fallback
    // (`tab.title || tab.url`), which `??` would not preserve.
    'typescript/prefer-nullish-coalescing': ['warn', { ignorePrimitives: { string: true } }],
    'typescript/prefer-optional-chain': 'warn',
    'typescript/prefer-readonly': 'warn',
    'typescript/prefer-regexp-exec': 'warn',
    'typescript/prefer-string-starts-ends-with': 'warn',
    'typescript/strict-void-return': 'warn',
    // Catches union members dropped from a switch that has no fallback. A
    // `default` arm is treated as covering the rest on purpose: one deliberate
    // fallback beats nine hand-written cases that say the same thing.
    'typescript/switch-exhaustiveness-check': [
      'error',
      { considerDefaultExhaustiveForUnions: true },
    ],

    // --- Suppressions that still fire under the narrowed categories ---
    // No correctness value for the patterns they match.
    'max-lines': 'off',
    'max-lines-per-function': 'off',
    'require-unicode-regexp': 'off',
    // Handlers and hooks are async by contract even when a given one has
    // nothing to await; oRPC and Fastify both expect a promise back.
    'require-await': 'off',
    'typescript/require-await': 'off',
    // The redundant arm it flags (`case '{slug}': default:`) is there to spell
    // out the full set of supported patterns next to the fallback.
    'unicorn/no-useless-switch-case': 'off',
    // Guards against `['1','2'].map(Number)`-style arity surprises, which
    // TypeScript already rejects; in practice it only fires on
    // single-argument helpers that are safe by signature.
    'unicorn/no-array-callback-reference': 'off',
    // Filesystem and git work is deliberately sequential. Parallelizing it
    // would reorder commits, race on the index, and exhaust descriptors on
    // a large repo.
    'no-await-in-loop': 'off',
    // Wiring modules and composed pages legitimately pull in many
    // collaborators; the count says nothing useful about coupling.
    'import/max-dependencies': 'off',
    // CSS side-effect imports are standard.
    'import/no-unassigned-import': 'off',
    'promise/always-return': 'off',
    'promise/catch-or-return': 'off',
    // Matches on the method name alone, so it also fires on
    // `BroadcastChannel.postMessage` and `chrome.runtime.Port.postMessage`,
    // neither of which takes a `targetOrigin` — passing one is a type error.
    'unicorn/require-post-message-target-origin': 'off',

    // --- Opt-ins from restriction/style/nursery ---
    // These categories are off wholesale, so each rule below is named
    // individually. They are ratchets that keep an existing discipline from
    // eroding rather than cleanups.
    // Escape hatches that should never become the default.
    'no-empty': 'error',
    'no-var': 'error',
    'typescript/no-empty-object-type': 'error',
    'typescript/no-explicit-any': 'error',
    'typescript/no-require-imports': 'error',
    // A blanket `oxlint-disable` silences every future rule too; force the
    // suppression to name what it is suppressing.
    'unicorn/no-abusive-eslint-disable': 'error',
    // `&`/`|` where `&&`/`||` was meant.
    'oxc/bad-bitwise-operator': 'error',
    // A cap on branching, not on size — `max-lines-per-function` is off above
    // because length says nothing useful, while twenty decision points in one
    // function is where a missed case hides. Off for `.tsx` in the override
    // below, where the count measures markup instead.
    // --- complexity family (shared package) ---
    ...complexityRules,
    // --- anti-slop (JS plugin, shared package) ---
    ...antiSlopRules,
    'prefer-arrow-callback': ['error', { allowNamedFunctions: true }],
    'prefer-const': 'error',
    'prefer-object-has-own': 'error',
    // Nursery, so an oxlint upgrade can change what they report. Both are set
    // at a level that will not break `main` if they get noisier.
    'import/export': 'error',
    'no-useless-assignment': 'warn',
    // Console output is a logger's job; a consumer scopes exceptions away in
    // its own override.
    'no-console': 'error',
    // Keeps an undocumented `process.env.X ?? ''` from appearing in a router.
    // A repo reads and types every variable in one env module, which turns
    // this rule off for itself with a named per-line disable.
    'node/no-process-env': 'error',
    // Brace-less single-statement bodies are where the "someone adds a second
    // statement" bug lives. Autofixable, so the cost is one commit.
    curly: 'error',
    // One name for the caught thing, everywhere.
    'object-shorthand': 'error',
    // `cause` is anti-slop's one allowed name for an unknown error parameter.
    'unicorn/catch-error-name': ['error', { ignore: ['^cause$'] }],
    // `T[]` over `Array<T>`.
    'typescript/array-type': ['error', { default: 'array' }],
    // --- perfectionist (JS plugin) ---
    // `partitionByComment` is load-bearing. Settings and config objects get
    // grouped under `// Appearance`-style headers; without partitioning,
    // sorting scatters each group and orphans every header comment.
    'perfectionist/sort-enums': ['warn', { partitionByComment: true, sortByValue: 'always' }],
    'perfectionist/sort-heritage-clauses': 'warn',
    'perfectionist/sort-interfaces': ['warn', { partitionByComment: true }],
    'perfectionist/sort-object-types': ['warn', { partitionByComment: true }],
    'perfectionist/sort-objects': ['warn', { partitionByComment: true }],
    // Plain alphabetical would wedge `className` between `aria-*` and `onClick`
    // on every element and split handlers from the props they act on. Grouping
    // keeps the semantic order the JSX already has and sorts within it.
    'perfectionist/sort-jsx-props': [
      'warn',
      {
        customGroups: [{ elementNamePattern: '^on[A-Z]', groupName: 'callback' }],
        groups: ['shorthand-prop', 'multiline-prop', 'unknown', 'callback'],
      },
    ],
    // `import * as X` in vendored code is exempted by `shadcnRulesOff`. This
    // guards hand-written code.
    'import/no-namespace': 'error',

    // --- Pedantic rules promoted to error ---
    // Already warnings via the category. These two encode a decision rather
    // than a preference, so a warning undersells them.
    // `{ null: 'ignore' }` keeps `x == null` as the null-or-undefined check.
    eqeqeq: ['error', 'always', { null: 'ignore' }],
    'no-throw-literal': 'error',
  },
};

export default rm3Config;
